Add new project
mabuge90/Portfolio pull request #10
Opened 2019-03-19 10:15 UTC by mabuge90

created form page to add new project, created css for form page, added upload file functionality and upload folder

2019-03-19 10:25 UTC, Liliya-V commented on upload.php
> +// Check if $uploadOk is set to 0 by an error
Do you need all these commented lines?

2019-03-19 10:26 UTC, Liliya-V commented on upload.php
> +//}
Do you need all these commented lines?

2019-03-19 10:34 UTC, Liliya-V commented on upload.php
> +    echo "Sorry, your file was not uploaded.";
Sorry file exists and Sorry file was not uploaded appear same time ( to fix in a next task?)

2019-03-19 10:35 UTC, Liliya-V commented on newProject.php
> +
delete extra lines

2019-03-19 10:36 UTC, Liliya-V commented on CSS/newProject.css
> +.addNewForm input[type=file] {
add a line to follow css standard

2019-03-19 10:36 UTC, Liliya-V commented on CSS/newProject.css
> +}
add a line to follow css standard

2019-03-19 16:10 UTC, mporam requested changes

2019-03-19 16:10 UTC, mporam commented on CSS/newProject.css
> +    color: white;
use hex everywhere, no color names

2019-03-19 16:10 UTC, mporam commented on newProject.php
> +        <h3>Project Title: </h3>
use `<label>` tags instead of h3

2019-03-19 16:10 UTC, mporam commented on upload.php
> +/**
remove unnecessary comment

2019-03-19 16:10 UTC, mporam commented on upload.php
> +$title = $_POST['title'];
no check to see if title or site exist?

2019-03-19 16:10 UTC, mporam commented on upload.php
> +if(isset($_POST["submit"])) {
PSR2 says:
`if (`

2019-03-20 10:33 UTC, mporam requested changes

2019-03-20 10:33 UTC, mporam commented on upload.php
> +if (empty($_POST['title'])) {
this doesnt work

2019-03-20 10:50 UTC, merged